name: "Install latest fish"
description: "Install the latest stable release of fish"
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-add-repository --yes --no-update ppa:fish-shell/release-3
        sudo apt-get update -qq
        sudo apt-get install --yes fish
      shell: bash
